#!/bin/bash
// Place into motioneyeos /data/etc/
GPIOA=17
GPIOB=27                                                                                                                                       
test -e /sys/class/gpio/gpio$GPIOA ||
  (echo $GPIOA > /sys/class/gpio/export \                                                                                                         && echo in > /sys/class/gpio/gpio$GPIOA/direction)
test -e /sys/class/gpio/gpio$GPIOB ||                                                                                                            (echo $GPIOB > /sys/class/gpio/export \
   && echo in > /sys/class/gpio/gpio$GPIOB/direction)

valA=$(cat /sys/class/gpio/gpio$GPIOA/value)
valB=$(cat /sys/class/gpio/gpio$GPIOB/value)                                                                                                   
if [ "$valA" == "1" ]; then                                                                                                                        GPIOA_text="CLOSED"
else
    GPIOA_text="OPEN"
fi                                                                                                                                             
if [ "$valB" == "1" ]; then                                                                                                                        GPIOB_text="CLOSED"
else
    GPIOB_text="OPEN"
fi
echo "B:$GPIOA_text  W:$GPIOB_text"
echo 5 1>&2
